# Generated by Django 4.0.8 on 2023-01-30 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness', models.CharField(blank=True, choices=[('Asthma', 'Asthma'), ('Cancer', 'Cancer'), ('Diabetes', 'Diabetes'), ('Heart Disease', 'Heart Disease'), ('Hypertension', 'Hypertension')], max_length=255, verbose_name='Illness')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, choices=[('Cardiologist', 'Cardiologist'), ('Dentist', 'Dentist'), ('Dermatologist', 'Dermatologist'), ('Endocrinologist', 'Endocrinologist'), ('Gastroenterologist', 'Gastroenterologist'), ('Neurologist', 'Neurologist')], max_length=255, verbose_name='Specialization')),
                ('patients', models.ManyToManyField(blank=True, related_name='doctor', to='users.patient')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
