# Generated by Django 4.0.8 on 2023-01-30 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_doctor_name_patient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
    ]
